export const mockRows = [
  {
    "Organization Name": "Autonomous Technologies Group",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/autonomous-technologies-group",
    "Last Funding Date": "2026-01-07",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "New York, New York, United States",
    Description:
      "Autonomous is an AI-powered fintech company that helps users manage investments and financial decisions independently.",
    "Last Funding Amount": "15000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "15000000",
    "Lead Investors": "BoxGroup, Y Combinator",
    Website: "https://becomeautonomous.xyz/",
  },
  {
    "Organization Name": "Hardline",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/hardline-31ab",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Los Angeles, California, United States",
    Description:
      "Hardline: a mobile-first, voice-powered app that turns jobsite calls & walkthroughs into clear, actionable project data",
    "Last Funding Amount": "2000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "2000000",
    "Lead Investors": "",
    Website: "https://www.hardlineapp.com/",
  },
  {
    "Organization Name": "100XBIO",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/100x-bioassay",
    "Last Funding Date": "2026-01-11",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Woburn, Massachusetts, United States",
    Description: "One-click immune R&D platform",
    "Last Funding Amount": "10000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "10000",
    "Lead Investors": "",
    Website: "https://www.100xbio.com/",
  },
  {
    "Organization Name": "Ucut inc",
    "Organization Name URL": "https://www.crunchbase.com/organization/ucut-inc",
    "Last Funding Date": "2026-01-02",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Boise, Idaho, United States",
    Description:
      "UCUT offers a service that brings barbers and stylists to a customer’s chosen location through a mobile app.",
    "Last Funding Amount": "5000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "5000000",
    "Lead Investors": "",
    Website: "https://ucutpro.com/",
  },
  {
    "Organization Name": "VisaPal",
    "Organization Name URL": "https://www.crunchbase.com/organization/visapal",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "New York, New York, United States",
    Description:
      "VisaPal provides online tools for managing visa applications and preparing required immigration documents.",
    "Last Funding Amount": "2000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "2000000",
    "Lead Investors": "",
    Website: "https://tryvisapal.com",
  },
  {
    "Organization Name": "Xella Health",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/xella-health",
    "Last Funding Date": "2026-01-11",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "11-50",
    "Headquarters Location": "San Francisco, California, United States",
    Description:
      "Xella Health is a women healthcare firm that unveils the major causes behind women health concern perimenopause to endometriosis.",
    "Last Funding Amount": "3700000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "3700000",
    "Lead Investors": "Precursor Ventures",
    Website: "https://joinxella.com/",
  },
  {
    "Organization Name": "Chamber",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/chamber-f81e",
    "Last Funding Date": "2026-01-06",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "San Francisco, California, United States",
    Description: "AI Infrastructure on Autopilot",
    "Last Funding Amount": "500000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "500000",
    "Lead Investors": "",
    Website: "https://www.usechamber.io",
  },
  {
    "Organization Name": "PantriApp",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/pantri-app",
    "Last Funding Date": "2026-01-06",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Houston, Texas, United States",
    Description:
      "Building the Household OS: AI infrastructure for the next generation of home services.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://pantri-app.com/",
  },
  {
    "Organization Name": "Anytool",
    "Organization Name URL": "https://www.crunchbase.com/organization/anytool",
    "Last Funding Date": "2026-01-07",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "",
    "Headquarters Location": "San Francisco, California, United States",
    Description:
      "Anytool is an applied research lab focused on transforming how teams build and use internal tools through AI collaboration.",
    "Last Funding Amount": "1000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "1000000",
    "Lead Investors": "Y Combinator",
    Website: "https://www.anytool.sh",
  },
  {
    "Organization Name": "Eatsy Orders",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/eatsy-orders",
    "Last Funding Date": "2026-01-07",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "11-50",
    "Headquarters Location": "Fort Lee, New Jersey, United States",
    Description:
      "Eatsy Orders offers a platform for restaurants to manage menus, orders, and operations through a unified digital system.",
    "Last Funding Amount": "100000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "100000",
    "Lead Investors": "",
    Website: "https://www.eatsyorders.com",
  },
  {
    "Organization Name": "Hearth Property",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/hearth-property",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "San Francisco, California, United States",
    Description: "AI Powered Property Management",
    "Last Funding Amount": "100000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "100000",
    "Lead Investors": "FIREBOARD INTELLIGENCE FORGE",
    Website: "https://www.hearthproperty.com/",
  },
  {
    "Organization Name": "SaltedHash Tech",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/saltedhash-tech-llc",
    "Last Funding Date": "2026-01-04",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "11-50",
    "Headquarters Location": "Sheridan, Wyoming, United States",
    Description:
      "Premier US Cybersecurity Firm | Offensive Security, Digital Forensics, Managed Defense & GRC | Securing Your Tomorrow",
    "Last Funding Amount": "25000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "25000",
    "Lead Investors": "Shariar Rahman",
    Website: "https://www.saltedhashtech.com",
  },
  {
    "Organization Name": "Exterview AI",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/exterview-ai",
    "Last Funding Date": "2026-01-10",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "51-100",
    "Headquarters Location": "San Francisco, California, United States",
    Description: "Agentic Talent Intelligence Platform",
    "Last Funding Amount": "1000000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "1000000",
    "Lead Investors": "",
    Website: "https://exterview.ai/",
  },
  {
    "Organization Name": "tmpo",
    "Organization Name URL": "https://www.crunchbase.com/organization/tmpo",
    "Last Funding Date": "2026-01-05",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "New York, New York, United States",
    Description:
      "tmpo is an innovative job-matching platform connecting employers and talent quickly through swipe-based recruiting",
    "Last Funding Amount": "127500",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "127500",
    "Lead Investors": "",
    Website: "https://www.tmpoapp.com/",
  },
  {
    "Organization Name": "Business For Teens",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/business-for-teens",
    "Last Funding Date": "2026-01-05",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "",
    "Headquarters Location": "Egypt, Arkansas, United States",
    Description:
      "Business For Teens is an education startup focused on teaching entrepreneurship and financial literacy to teenagers.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "Salah Abo El Magd",
    Website: "https://growacademy.me",
  },
  {
    "Organization Name": "HyBotX",
    "Organization Name URL": "https://www.crunchbase.com/organization/hybotx",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "",
    "Headquarters Location": "Rockville, Maryland, United States",
    Description:
      "HyBotX is a robotics power technology company focused on enabling long-duration.",
    "Last Funding Amount": "200000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "200000",
    "Lead Investors": "FasterCapital, Hesham Zreik",
    Website: "",
  },
  {
    "Organization Name": "EyeTally.AI",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/eyetally-ai",
    "Last Funding Date": "2026-01-06",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Spokane, Washington, United States",
    Description:
      "EyeTally.AI is a retail tech company that offers AI powered back office software for retailers.",
    "Last Funding Amount": "10000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "10000",
    "Lead Investors": "",
    Website: "https://eyetally.ai/",
  },
  {
    "Organization Name": "Cognirum",
    "Organization Name URL": "https://www.crunchbase.com/organization/cognirum",
    "Last Funding Date": "2026-01-06",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "11-50",
    "Headquarters Location": "Novato, California, United States",
    Description:
      "Cognirum is a SaaS company that offers AI tools for business automation services.",
    "Last Funding Amount": "8700",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "8700",
    "Lead Investors": "",
    Website: "https://cognirum.com/",
  },
  {
    "Organization Name": "Paivana",
    "Organization Name URL": "https://www.crunchbase.com/organization/paivana",
    "Last Funding Date": "2026-01-09",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "",
    "Headquarters Location": "Lewes, Delaware, United States",
    Description:
      "Paivana is an AI driven fintech company that offers AI agent enabled cash and payment system for instant account-free transactions.",
    "Last Funding Amount": "1500",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "1500",
    "Lead Investors": "",
    Website: "https://paivana.ai/",
  },
  {
    "Organization Name": "Clikyo",
    "Organization Name URL": "https://www.crunchbase.com/organization/clikyo",
    "Last Funding Date": "2026-01-08",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Atlanta, Georgia, United States",
    Description:
      "Next-generation social media platform empowering creators through AI, creativity, and authentic global connection.",
    "Last Funding Amount": "1000",
    "Last Funding Amount Currency": "USD",
    "Last Funding Amount (in USD)": "1000",
    "Lead Investors": "",
    Website: "https://clikyo.com/",
  },
  {
    "Organization Name": "Visorix",
    "Organization Name URL": "https://www.crunchbase.com/organization/visorix",
    "Last Funding Date": "2026-01-08",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "La Crosse, Wisconsin, United States",
    Description:
      "Visorix is a VR ecosystem builder developing the Virtara—a snap-on, 5.7K stereoscopic camera system for the creator economy. Patent Pending",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://visorix.net/",
  },
  {
    "Organization Name": "PeKe Labs",
    "Organization Name URL": "https://www.crunchbase.com/organization/peke-labs",
    "Last Funding Date": "2026-01-06",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Boston, Massachusetts, United States",
    Description:
      "PeKe Labs builds wearable gesture-control hardware for seamless, private human–AI interaction.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://www.pekelabs.com/",
  },
  {
    "Organization Name": "Legal Extract AI",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/legal-extract-ai",
    "Last Funding Date": "2026-01-09",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Newark, New Jersey, United States",
    Description:
      "Legal Extract AI offers tools that extract structured data and key terms from legal documents.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://www.legalextract.ai",
  },
  {
    "Organization Name": "Lexitio",
    "Organization Name URL": "https://www.crunchbase.com/organization/lexitio",
    "Last Funding Date": "2026-01-05",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "New York, New York, United States",
    Description: "Legal AI, SaaS, OSINT, CRM, Deep Tech",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "http://lexitio.com",
  },
  {
    "Organization Name": "Ethicos Health",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/ethicos-health",
    "Last Funding Date": "2026-01-07",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Nashville, Tennessee, United States",
    Description:
      "Ethicos Health is a Nashville-based healthcare technology startup with an AI-enabled platform designed to manage specialty pharmacy costs.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://ethicoshealth.com/",
  },
  {
    "Organization Name": "Backboard.io",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/backboard-io",
    "Last Funding Date": "2026-01-07",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Ottawa, Ontario, Canada",
    Description:
      "Backboard.io provides developers a single stateful interface to more than 400 LLMs and SLMs for app development.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "Mistral Venture Partners",
    Website: "https://backboard.io/",
  },
  {
    "Organization Name": "COYA",
    "Organization Name URL": "https://www.crunchbase.com/organization/coya-5d46",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "San Francisco, California, United States",
    Description:
      "COYA is a social networking platform for gamers to find teammates, join communities, and connect with players by game, region, & playstyle.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://www.coya.gg",
  },
  {
    "Organization Name": "Campsite Games",
    "Organization Name URL":
      "https://www.crunchbase.com/organization/campsite-games",
    "Last Funding Date": "2026-01-01",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Los Angeles, California, United States",
    Description:
      "Campsite Games is a fully remote independent game studio, building a Social Action Roleplaying Game",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://www.campsitegames.com",
  },
  {
    "Organization Name": "Colare",
    "Organization Name URL": "https://www.crunchbase.com/organization/colare",
    "Last Funding Date": "2026-01-05",
    "Last Funding Type": "Pre-Seed",
    "Number of Employees": "1-10",
    "Headquarters Location": "Toronto, Ontario, Canada",
    Description: "AI-powered hiring platform to hire engineers faster.",
    "Last Funding Amount": "",
    "Last Funding Amount Currency": "",
    "Last Funding Amount (in USD)": "",
    "Lead Investors": "",
    Website: "https://colare.co/",
  },
];
