export const mockRows = [
  {
    organizationName: "Autonomous Technologies Group",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/autonomous-technologies-group",
    lastFundingDate: "2026-01-07",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "New York, New York, United States",
    description:
      "Autonomous is an AI-powered fintech company that helps users manage investments and financial decisions independently.",
    lastFundingAmount: 15000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 15000000,
    leadInvestors: ["BoxGroup", "Y Combinator"],
    website: "https://becomeautonomous.xyz/",
  },
  {
    organizationName: "Hardline",
    organizationNameUrl: "https://www.crunchbase.com/organization/hardline-31ab",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Los Angeles, California, United States",
    description:
      "Hardline: a mobile-first, voice-powered app that turns jobsite calls & walkthroughs into clear, actionable project data",
    lastFundingAmount: 2000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 2000000,
    leadInvestors: [],
    website: "https://www.hardlineapp.com/",
  },
  {
    organizationName: "100XBIO",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/100x-bioassay",
    lastFundingDate: "2026-01-11",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Woburn, Massachusetts, United States",
    description: "One-click immune R&D platform",
    lastFundingAmount: 10000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 10000,
    leadInvestors: [],
    website: "https://www.100xbio.com/",
  },
  {
    organizationName: "Ucut inc",
    organizationNameUrl: "https://www.crunchbase.com/organization/ucut-inc",
    lastFundingDate: "2026-01-02",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Boise, Idaho, United States",
    description:
      "UCUT offers a service that brings barbers and stylists to a customer’s chosen location through a mobile app.",
    lastFundingAmount: 5000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 5000000,
    leadInvestors: [],
    website: "https://ucutpro.com/",
  },
  {
    organizationName: "VisaPal",
    organizationNameUrl: "https://www.crunchbase.com/organization/visapal",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "New York, New York, United States",
    description:
      "VisaPal provides online tools for managing visa applications and preparing required immigration documents.",
    lastFundingAmount: 2000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 2000000,
    leadInvestors: [],
    website: "https://tryvisapal.com",
  },
  {
    organizationName: "Xella Health",
    organizationNameUrl: "https://www.crunchbase.com/organization/xella-health",
    lastFundingDate: "2026-01-11",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "11-50",
    headquartersLocation: "San Francisco, California, United States",
    description:
      "Xella Health is a women healthcare firm that unveils the major causes behind women health concern perimenopause to endometriosis.",
    lastFundingAmount: 3700000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 3700000,
    leadInvestors: ["Precursor Ventures"],
    website: "https://joinxella.com/",
  },
  {
    organizationName: "Chamber",
    organizationNameUrl: "https://www.crunchbase.com/organization/chamber-f81e",
    lastFundingDate: "2026-01-06",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "San Francisco, California, United States",
    description: "AI Infrastructure on Autopilot",
    lastFundingAmount: 500000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 500000,
    leadInvestors: [],
    website: "https://www.usechamber.io",
  },
  {
    organizationName: "PantriApp",
    organizationNameUrl: "https://www.crunchbase.com/organization/pantri-app",
    lastFundingDate: "2026-01-06",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Houston, Texas, United States",
    description:
      "Building the Household OS: AI infrastructure for the next generation of home services.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://pantri-app.com/",
  },
  {
    organizationName: "Anytool",
    organizationNameUrl: "https://www.crunchbase.com/organization/anytool",
    lastFundingDate: "2026-01-07",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: null,
    headquartersLocation: "San Francisco, California, United States",
    description:
      "Anytool is an applied research lab focused on transforming how teams build and use internal tools through AI collaboration.",
    lastFundingAmount: 1000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 1000000,
    leadInvestors: ["Y Combinator"],
    website: "https://www.anytool.sh",
  },
  {
    organizationName: "Eatsy Orders",
    organizationNameUrl: "https://www.crunchbase.com/organization/eatsy-orders",
    lastFundingDate: "2026-01-07",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "11-50",
    headquartersLocation: "Fort Lee, New Jersey, United States",
    description:
      "Eatsy Orders offers a platform for restaurants to manage menus, orders, and operations through a unified digital system.",
    lastFundingAmount: 100000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 100000,
    leadInvestors: [],
    website: "https://www.eatsyorders.com",
  },
  {
    organizationName: "Hearth Property",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/hearth-property",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "San Francisco, California, United States",
    description: "AI Powered Property Management",
    lastFundingAmount: 100000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 100000,
    leadInvestors: ["FIREBOARD INTELLIGENCE FORGE"],
    website: "https://www.hearthproperty.com/",
  },
  {
    organizationName: "SaltedHash Tech",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/saltedhash-tech-llc",
    lastFundingDate: "2026-01-04",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "11-50",
    headquartersLocation: "Sheridan, Wyoming, United States",
    description:
      "Premier US Cybersecurity Firm | Offensive Security, Digital Forensics, Managed Defense & GRC | Securing Your Tomorrow",
    lastFundingAmount: 25000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 25000,
    leadInvestors: ["Shariar Rahman"],
    website: "https://www.saltedhashtech.com",
  },
  {
    organizationName: "Exterview AI",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/exterview-ai",
    lastFundingDate: "2026-01-10",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "51-100",
    headquartersLocation: "San Francisco, California, United States",
    description: "Agentic Talent Intelligence Platform",
    lastFundingAmount: 1000000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 1000000,
    leadInvestors: [],
    website: "https://exterview.ai/",
  },
  {
    organizationName: "tmpo",
    organizationNameUrl: "https://www.crunchbase.com/organization/tmpo",
    lastFundingDate: "2026-01-05",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "New York, New York, United States",
    description:
      "tmpo is an innovative job-matching platform connecting employers and talent quickly through swipe-based recruiting",
    lastFundingAmount: 127500,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 127500,
    leadInvestors: [],
    website: "https://www.tmpoapp.com/",
  },
  {
    organizationName: "Business For Teens",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/business-for-teens",
    lastFundingDate: "2026-01-05",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: null,
    headquartersLocation: "Egypt, Arkansas, United States",
    description:
      "Business For Teens is an education startup focused on teaching entrepreneurship and financial literacy to teenagers.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: ["Salah Abo El Magd"],
    website: "https://growacademy.me",
  },
  {
    organizationName: "HyBotX",
    organizationNameUrl: "https://www.crunchbase.com/organization/hybotx",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: null,
    headquartersLocation: "Rockville, Maryland, United States",
    description:
      "HyBotX is a robotics power technology company focused on enabling long-duration.",
    lastFundingAmount: 200000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 200000,
    leadInvestors: ["FasterCapital", "Hesham Zreik"],
    website: null,
  },
  {
    organizationName: "EyeTally.AI",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/eyetally-ai",
    lastFundingDate: "2026-01-06",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Spokane, Washington, United States",
    description:
      "EyeTally.AI is a retail tech company that offers AI powered back office software for retailers.",
    lastFundingAmount: 10000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 10000,
    leadInvestors: [],
    website: "https://eyetally.ai/",
  },
  {
    organizationName: "Cognirum",
    organizationNameUrl: "https://www.crunchbase.com/organization/cognirum",
    lastFundingDate: "2026-01-06",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "11-50",
    headquartersLocation: "Novato, California, United States",
    description:
      "Cognirum is a SaaS company that offers AI tools for business automation services.",
    lastFundingAmount: 8700,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 8700,
    leadInvestors: [],
    website: "https://cognirum.com/",
  },
  {
    organizationName: "Paivana",
    organizationNameUrl: "https://www.crunchbase.com/organization/paivana",
    lastFundingDate: "2026-01-09",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: null,
    headquartersLocation: "Lewes, Delaware, United States",
    description:
      "Paivana is an AI driven fintech company that offers AI agent enabled cash and payment system for instant account-free transactions.",
    lastFundingAmount: 1500,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 1500,
    leadInvestors: [],
    website: "https://paivana.ai/",
  },
  {
    organizationName: "Clikyo",
    organizationNameUrl: "https://www.crunchbase.com/organization/clikyo",
    lastFundingDate: "2026-01-08",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Atlanta, Georgia, United States",
    description:
      "Next-generation social media platform empowering creators through AI, creativity, and authentic global connection.",
    lastFundingAmount: 1000,
    lastFundingAmountCurrency: "USD",
    lastFundingAmountUsd: 1000,
    leadInvestors: [],
    website: "https://clikyo.com/",
  },
  {
    organizationName: "Visorix",
    organizationNameUrl: "https://www.crunchbase.com/organization/visorix",
    lastFundingDate: "2026-01-08",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "La Crosse, Wisconsin, United States",
    description:
      "Visorix is a VR ecosystem builder developing the Virtara—a snap-on, 5.7K stereoscopic camera system for the creator economy. Patent Pending",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://visorix.net/",
  },
  {
    organizationName: "PeKe Labs",
    organizationNameUrl: "https://www.crunchbase.com/organization/peke-labs",
    lastFundingDate: "2026-01-06",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Boston, Massachusetts, United States",
    description:
      "PeKe Labs builds wearable gesture-control hardware for seamless, private human–AI interaction.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://www.pekelabs.com/",
  },
  {
    organizationName: "Legal Extract AI",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/legal-extract-ai",
    lastFundingDate: "2026-01-09",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Newark, New Jersey, United States",
    description:
      "Legal Extract AI offers tools that extract structured data and key terms from legal documents.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://www.legalextract.ai",
  },
  {
    organizationName: "Lexitio",
    organizationNameUrl: "https://www.crunchbase.com/organization/lexitio",
    lastFundingDate: "2026-01-05",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "New York, New York, United States",
    description: "Legal AI, SaaS, OSINT, CRM, Deep Tech",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "http://lexitio.com",
  },
  {
    organizationName: "Ethicos Health",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/ethicos-health",
    lastFundingDate: "2026-01-07",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Nashville, Tennessee, United States",
    description:
      "Ethicos Health is a Nashville-based healthcare technology startup with an AI-enabled platform designed to manage specialty pharmacy costs.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://ethicoshealth.com/",
  },
  {
    organizationName: "Backboard.io",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/backboard-io",
    lastFundingDate: "2026-01-07",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Ottawa, Ontario, Canada",
    description:
      "Backboard.io provides developers a single stateful interface to more than 400 LLMs and SLMs for app development.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: ["Mistral Venture Partners"],
    website: "https://backboard.io/",
  },
  {
    organizationName: "COYA",
    organizationNameUrl: "https://www.crunchbase.com/organization/coya-5d46",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "San Francisco, California, United States",
    description:
      "COYA is a social networking platform for gamers to find teammates, join communities, and connect with players by game, region, & playstyle.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://www.coya.gg",
  },
  {
    organizationName: "Campsite Games",
    organizationNameUrl:
      "https://www.crunchbase.com/organization/campsite-games",
    lastFundingDate: "2026-01-01",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Los Angeles, California, United States",
    description:
      "Campsite Games is a fully remote independent game studio, building a Social Action Roleplaying Game",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://www.campsitegames.com",
  },
  {
    organizationName: "Colare",
    organizationNameUrl: "https://www.crunchbase.com/organization/colare",
    lastFundingDate: "2026-01-05",
    lastFundingType: "Pre-Seed",
    numberOfEmployees: "1-10",
    headquartersLocation: "Toronto, Ontario, Canada",
    description: "AI-powered hiring platform to hire engineers faster.",
    lastFundingAmount: null,
    lastFundingAmountCurrency: null,
    lastFundingAmountUsd: null,
    leadInvestors: [],
    website: "https://colare.co/",
  },
];
